### ISSUE TITLE
Problem with dataloaders

### ISSUE THREAD

**Issue by WiktorSa** [c-dowling/eeg_cursor_bci#27]
So I think I have figured out what is causing the error with dataloaders

1. The length of concatenated datasets isn't always divisible by batch_size. This generates error in colab because the dataloader is created with the incorrect length of data and that makes data corrupted and impossible to read.
2. The only way to fix 1 using the current code is to manually copy everything into numpy arrays (because ConcatDataset doesn't support indexing in an advanced way)

I will probably rewrite the dataloaders.py so that it would work with these problems but it would be good if you also took look into that.

**Comment by RogerAylagas** [comment]
Try to run the reorganized code. It is weird that this is the problem as usually datasets size is not divisible by batch size. If the error persists pls post the error log here :)

**Comment by WiktorSa** [comment]
C:\Users\User\AppData\Local\Programs\Python\Python39\python.exe C:/Users/User/Desktop/eeg_cursor_bci-pipeline/main.py
Traceback (most recent call last):
  File "C:\Users\User\Desktop\eeg_cursor_bci-pipeline\main.py", line 50, in <module>
    main()
  File "C:\Users\User\Desktop\eeg_cursor_bci-pipeline\main.py", line 46, in main
    train(model, {'Train': trainloader, 'Valid': validloader}, optimizer, criterion, params, callback=early_stopping)
  File "C:\Users\User\Desktop\eeg_cursor_bci-pipeline\utils.py", line 57, in train
    bar = tqdm(enumerate(dataloaders[phase]), total=len(dataloaders[phase]), desc=f'Epoch {epoch:>2} ({phase})')
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\h5py\_hl\base.py", line 372, in __getnewargs__
    raise TypeError("h5py objects cannot be pickled")
TypeError: h5py objects cannot be pickled

**Comment by WiktorSa** [comment]
https://groups.google.com/g/h5py/c/dwv9K-9esu8
I found this. Maybe this can help.

**Comment by WiktorSa** [comment]
https://github.com/DaanVanVugt/h5pickle
This library could solve the problem. Download it and check if this doesn't crash on your computer

**Comment by WiktorSa** [comment]
Just swap 
import h5pickle as h5py
with
import h5py

in dataloaders.py

**Comment by RogerAylagas** [comment]
I think this should be solved with the pull request https://github.com/c-dowling/eeg_cursor_bci/pull/28
